import {useMemo,useRef,useState} from "react";
import {readStudentWorkbook,readTeacherWorkbook,exportScheduleXlsx} from "./excel";
import {createScheduleFromAi,createStudentSchedule,hasArtDayException,type AiAssignment,type ScheduleOptions,type ScheduleResult,type Student,type TeacherRecord} from "./scheduler";

const DEFAULT_WEEKDAY="14:40-16:10, 16:20-17:50, 18:00-19:30";
const DEFAULT_FRIDAY="09:00-10:30, 10:40-12:10, 14:40-16:10, 16:20-17:50, 18:00-19:30";
const DEFAULT_SATURDAY="09:00-10:30, 10:40-12:10, 12:40-14:10, 14:20-15:50, 16:00-17:30";
const slots=(text:string)=>text.split(/[,;\n]/).map(x=>x.trim()).filter(x=>/^\d{1,2}:\d{2}\s*[-_]\s*\d{1,2}:\d{2}$/.test(x)).map(x=>x.replace('_','-'));
const wait=(milliseconds:number)=>new Promise(resolve=>setTimeout(resolve,milliseconds));

function UploadCard({count,fileName,onFile}:{count:number;fileName:string;onFile:(file:File)=>void}){
  const input=useRef<HTMLInputElement>(null);return <div className={`uploadCard ${count?"done":""}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)onFile(f)}}><div className="cardTop"><div className="uploadIcon">X</div><b>{count?"✓ HAZIR":"XLSX"}</b></div><h3>Öğrenci Excel’i</h3><p>{count?`${count} öğrenci okundu · ${fileName}`:"Öğrenci adı, ders kodları, sınıf, okul ve varsa vardiya bilgileri"}</p><button className="linkBtn" onClick={()=>input.current?.click()}>{count?"Excel’i değiştir":"Excel dosyası seç"} →</button><a href="/ornek-ogrenciler.xlsx" download>Örnek Excel şablonunu indir</a><input ref={input} hidden type="file" accept=".xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/></div>
}

function TeacherUploadCard({count,fileName,onFile}:{count:number;fileName:string;onFile:(file:File)=>void}){const input=useRef<HTMLInputElement>(null);return <div className={`uploadCard ${count?"done":""}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)onFile(f)}}><div className="cardTop"><div className="uploadIcon">Ö</div><b>{count?"✓ HAZIR":"XLSX"}</b></div><h3>Öğretmen Excel’i</h3><p>{count?`${count} öğretmen okundu · ${fileName}`:"Öğretmen adı, ders kodları ve uygun/uygun olmayan saatler"}</p><button className="linkBtn" onClick={()=>input.current?.click()}>{count?"Excel’i değiştir":"Excel dosyası seç"} →</button><a href="/ornek-ogretmenler.xlsx" download>Örnek öğretmen şablonunu indir</a><input ref={input} hidden type="file" accept=".xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/></div>}

function Toggle({checked,onChange,label,help}:{checked:boolean;onChange:(v:boolean)=>void;label:string;help:string}){return <label className="toggle"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span/><div><b>{label}</b><small>{help}</small></div></label>}

export default function App(){
  const [students,setStudents]=useState<Student[]>([]),[teachers,setTeachers]=useState<TeacherRecord[]>([]),[fileName,setFileName]=useState(""),[teacherFileName,setTeacherFileName]=useState(""),[readWarnings,setReadWarnings]=useState<string[]>([]),[teacherWarnings,setTeacherWarnings]=useState<string[]>([]),[error,setError]=useState(""),[result,setResult]=useState<ScheduleResult|null>(null),[tab,setTab]=useState<"student"|"group"|"teacher"|"issues">("student"),[studentFilter,setStudentFilter]=useState(""),[teacherFilter,setTeacherFilter]=useState(""),[busy,setBusy]=useState(false);
  const [days,setDays]=useState(["Salı","Çarşamba","Perşembe","Cuma","Cumartesi"]),[weekdayText,setWeekdayText]=useState(DEFAULT_WEEKDAY),[fridayText,setFridayText]=useState(DEFAULT_FRIDAY),[saturdayText,setSaturdayText]=useState(DEFAULT_SATURDAY),[teacherMapText,setTeacherMapText]=useState(""),[customRules,setCustomRules]=useState(""),[naturalRules,setNaturalRules]=useState("");
  const [aiProvider,setAiProvider]=useState<"auto"|"openai"|"anthropic">("auto");
  const [preventStudent,setPreventStudent]=useState(true),[preventTeacher,setPreventTeacher]=useState(true),[privateSaturday,setPrivateSaturday]=useState(true),[morningWeekday,setMorningWeekday]=useState(true),[preservePrevious,setPreservePrevious]=useState(true),[mergeNeeded,setMergeNeeded]=useState(true),[mergeMax,setMergeMax]=useState(8),[maxStudentDaily,setMaxStudentDaily]=useState(2),[maxTeacherDaily,setMaxTeacherDaily]=useState(6);
  const options=():ScheduleOptions=>({days,weekdaySlots:slots(weekdayText),fridaySlots:slots(fridayText),saturdaySlots:slots(saturdayText),teacherMapText,customRules,teacherAvailability:teachers,preventStudentConflicts:preventStudent,preventTeacherConflicts:preventTeacher,preferPrivateSaturday:privateSaturday,preferMorningWeekday:morningWeekday,preservePrevious,mergeWhenNeeded:mergeNeeded,mergeMax,maxStudentDaily,maxTeacherDaily});
  const read=async(file:File)=>{try{setError("");setBusy(true);const parsed=await readStudentWorkbook(file);setStudents(parsed.students);setReadWarnings(parsed.warnings);setFileName(file.name);setResult(null)}catch(e){setError(e instanceof Error?e.message:"Excel okunamadı.")}finally{setBusy(false)}};
  const readTeachers=async(file:File)=>{try{setError("");setBusy(true);const parsed=await readTeacherWorkbook(file);setTeachers(parsed.teachers);setTeacherWarnings(parsed.warnings);setTeacherFileName(file.name);setTeacherMapText(parsed.teachers.flatMap(t=>t.patterns.map(pattern=>`${pattern}=${t.name}`)).join("\n"));setResult(null)}catch(e){setError(e instanceof Error?e.message:"Öğretmen Excel’i okunamadı.")}finally{setBusy(false)}};
  const showResult=(next:ScheduleResult)=>{setResult({...next,warnings:[...readWarnings,...teacherWarnings,...next.warnings]});setStudentFilter(next.studentRows[0]?.student.name||"");setTeacherFilter(next.teacherNames[0]||"");setTab("student");setTimeout(()=>document.getElementById("results")?.scrollIntoView({behavior:"smooth"}),50)};
  const validateInput=()=>{const o=options();if(!students.length){setError("Önce öğrenci Excel’ini yükleyin.");return null}if(!teachers.length&&!teacherMapText.trim()){setError("Öğretmen Excel’ini yükleyin veya ders kodu → öğretmen eşlemesi yazın.");return null}if(!o.days.length||!o.weekdaySlots.length||!o.saturdaySlots.length){setError("Çalışma günü ve geçerli saat bloklarını kontrol edin.");return null}return o};
  const generate=()=>{const o=validateInput();if(!o)return;setError("");showResult(createStudentSchedule(students,o))};
  const generateAi=async()=>{const o=validateInput();if(!o)return;try{setBusy(true);setError("");const safeStudents=students.map(s=>({id:s.id,grade:s.grade,school:s.school,shift:s.shift,color:s.color,artDayException:hasArtDayException(s),unavailable:s.unavailable,lessons:s.lessons.slice(0,2).map(l=>({code:l.code,previousDay:l.previousDay,previousTime:l.previousTime}))})),jobId=crypto.randomUUID();const started=await fetch("/.netlify/functions/generate-schedule-background",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jobId,provider:aiProvider,students:safeStudents,options:o})});if(!started.ok&&started.status!==202)throw new Error("AI program işi başlatılamadı.");let data:Record<string,any>|undefined;for(let attempt=0;attempt<240;attempt++){await wait(2500);const status=await fetch(`/.netlify/functions/schedule-status?id=${encodeURIComponent(jobId)}`,{cache:"no-store"});if(status.status===202)continue;const body=await status.json();if(!status.ok)throw new Error(body.error||"AI programı oluşturulamadı.");data=body;break}if(!data)throw new Error("AI programı zamanında tamamlanamadı; yeniden deneyin.");const next=createScheduleFromAi(students,o,data.assignments as AiAssignment[],[`${data.provider} · ${data.model} ile program önerisi oluşturuldu.`,...(data.warnings||[])]);showResult(next)}catch(e){setError(e instanceof Error?e.message:"AI programı oluşturulamadı.")}finally{setBusy(false)}};
  const interpret=async()=>{if(!naturalRules.trim())return;try{setBusy(true);setError("");const response=await fetch("/.netlify/functions/interpret-rules",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text:naturalRules,provider:aiProvider,courseCodes:[...new Set(students.flatMap(s=>s.lessons.map(l=>l.code)))]})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Kural API’si yanıt vermedi.");if(data.teacherMappings?.length)setTeacherMapText((x=>[x,...data.teacherMappings].filter(Boolean).join("\n"))(teacherMapText));if(data.ruleLines?.length)setCustomRules((x=>[x,...data.ruleLines].filter(Boolean).join("\n"))(customRules))}catch(e){setError(e instanceof Error?e.message:"Kural yorumlanamadı.")}finally{setBusy(false)}};
  const studentRows=useMemo(()=>result?.studentRows.filter(x=>!studentFilter||x.student.name===studentFilter)||[],[result,studentFilter]);
  const teacherRows=useMemo(()=>result?.rows.filter(x=>!teacherFilter||x.teacher===teacherFilter)||[],[result,teacherFilter]);
  const placedStudentCount=useMemo(()=>new Set(result?.studentRows.map(x=>x.student.id)||[]).size,[result]);
  return <main>
    <header className="topbar"><a className="brand" href="#">Ders<span>Plan</span></a><nav><a href="#setup">Excel ve kısıtlar</a><a href="#how">Nasıl çalışır?</a></nav><div className="privacy"><i/> Ham Excel’ler cihazda kalır</div></header>
    <section className="hero"><div className="eyebrow">ÖĞRENCİ + ÖĞRETMEN PLANLAMA</div><h1>İki Excel’i yükleyin,<br/><em>program hazır.</em></h1><p>Öğrencileri ders kodlarına göre gruplandırın; öğretmenlerin uygun saatlerini ikinci Excel’den okuyun. Güçlü AI veya yerel algoritma çakışmasız programı hazırlasın.</p><a className="heroCta" href="#setup">Excel’leri yükle ↓</a><div className="heroStats"><div><strong>1</strong><span>Öğrenci Excel’i</span></div><div><strong>1</strong><span>Öğretmen Excel’i</span></div><div><strong>PDF</strong><span>Yönetim raporu</span></div></div></section>
    <section className="workspace" id="setup"><div className="sectionHead"><div><span>PROGRAM MODÜLÜ</span><h2>Excel ve kısıtları ekleyin</h2></div><div className="stepCount">Tamamı tarayıcıda</div></div>{error&&<div className="alert" role="alert">⚠ {error}</div>}
      <div className="moduleGrid"><UploadCard count={students.length} fileName={fileName} onFile={read}/><TeacherUploadCard count={teachers.length} fileName={teacherFileName} onFile={readTeachers}/><div className="settingsPanel"><div className="panelTitle"><div className="uploadIcon">K</div><div><b>Planlama kısıtları</b><small>Ana günler: 7. sınıf Salı, 8. sınıf Çarşamba, turuncular Cumartesi; Müzik/Resim Perşembe veya Cuma istisnası</small></div></div><div className="days">{["Salı","Çarşamba","Perşembe","Cuma","Cumartesi"].map(day=><button key={day} className={days.includes(day)?"selected":""} onClick={()=>setDays(x=>x.includes(day)?x.filter(y=>y!==day):[...x,day])}>{day}</button>)}</div><div className="slotFields"><label>Hafta içi öğleden sonra<textarea value={weekdayText} onChange={e=>setWeekdayText(e.target.value)}/></label><label>Cuma (sabah istisnası dahil)<textarea value={fridayText} onChange={e=>setFridayText(e.target.value)}/></label><label>Cumartesi (09:00 yalnız BYF/Proje)<textarea value={saturdayText} onChange={e=>setSaturdayText(e.target.value)}/></label></div></div></div>
      <div className="constraintGrid"><div className="constraintBox"><h3>Hazır kurallar</h3><Toggle checked={preventStudent} onChange={setPreventStudent} label="Öğrenci çakışmasını engelle" help="Aynı öğrenci aynı anda iki grupta olmaz"/><Toggle checked={preventTeacher} onChange={setPreventTeacher} label="Öğretmen çakışmasını engelle" help="Kod eşlemesi yapılan öğretmen aynı anda tek derste olur"/><Toggle checked={privateSaturday} onChange={setPrivateSaturday} label="Özel/şehir dışı okulu Cumartesiye al" help="Özel, tam gün ve şehir dışı okul adlarına öncelik verir"/><Toggle checked={morningWeekday} onChange={setMorningWeekday} label="Sabahçı öğrenciyi hafta içine al" help="Vardiya sütununda Sabah yazanları Salı gününe yaklaştırır"/><Toggle checked={preservePrevious} onChange={setPreservePrevious} label="Geçen yılın saatini korumaya çalış" help="Ders hücresindeki eski gün ve saati tercih puanı olarak kullanır"/><Toggle checked={mergeNeeded} onChange={setMergeNeeded} label="Aynı aşamadaki küçük grupları gerektiğinde birleştir" help="Aynı öğretmenin programı sığmazsa uyumlu kodları birleştirir"/><div className="numberFields"><label>Birleşik grup üst sınırı<input type="number" min="2" max="30" value={mergeMax} onChange={e=>setMergeMax(Number(e.target.value)||8)}/></label><label>Öğrenci günlük ders üst sınırı<input type="number" min="1" max="8" value={maxStudentDaily} onChange={e=>setMaxStudentDaily(Number(e.target.value)||2)}/></label><label>Öğretmen günlük grup üst sınırı<input type="number" min="1" max="12" value={maxTeacherDaily} onChange={e=>setMaxTeacherDaily(Number(e.target.value)||6)}/></label></div></div>
        <div className="constraintBox"><h3>Ders kodu → öğretmen</h3><p>Bir ders kodunu veya kod ailesini öğretmene bağlayın. Her satıra bir eşleme yazın.</p><textarea className="largeText" value={teacherMapText} onChange={e=>setTeacherMapText(e.target.value)} placeholder={"PMAT*=Zafer Savaş Kıvılcım\nÖFİZ*=Merve Çeçen\nPİNG*=Zeynep Güler"}/><small><code>*</code> aynı önekle başlayan bütün ders kodlarını kapsar. Tam kod da kullanabilirsiniz.</small><h3 className="subheading">Yapılandırılmış özel kurallar</h3><textarea className="largeText" value={customRules} onChange={e=>setCustomRules(e.target.value)} placeholder={"PMAT129 Cumartesi 09:00-10:30\nÖMAT111 birleşmesin\nZafer Savaş Kıvılcım yalnız Salı, Cumartesi\nZafer Savaş Kıvılcım günde en fazla 4 ders\nAYŞE DİDEM KORUOĞLU Salı uygun değil"}/></div>
        <div className="constraintBox aiBox"><h3>Serbest metin / API</h3><p>Kuralınızı normal cümleyle yazın. OpenAI veya Claude, metni yapılandırılmış kurallara dönüştürür.</p><label className="providerLabel">AI sağlayıcısı<select value={aiProvider} onChange={e=>setAiProvider(e.target.value as "auto"|"openai"|"anthropic")}><option value="auto">Otomatik — güçlü OpenAI arka planda</option><option value="anthropic">Claude</option><option value="openai">OpenAI</option></select></label><textarea className="largeText" value={naturalRules} onChange={e=>setNaturalRules(e.target.value)} placeholder="Zafer Hoca yalnız Salı ve Cumartesi çalışsın. PMAT129 Cumartesi sabah ilk ders olsun. Ayşe Salı gelemez."/><button className="secondary" onClick={interpret} disabled={busy||!naturalRules.trim()}>AI ile kurala dönüştür</button><div className="apiNote"><b>API isteğe bağlıdır.</b> Program güçlü modelle arka planda hazırlanır; kesin kurallar sonuç doğrulamasında ayrıca uygulanır. Büyük listeler birkaç dakika sürebilir.</div></div></div>
      <div className="actionRow"><p><b>Ana program kuralı:</b> Her öğrenci yalnız bir gün gelir ve iki dersi aynı gün art arda iki periyotta olur. Normal öğrenciler Salı/Çarşamba/Cumartesi düzeninde kalır; Müzik veya Resim alanı olanlar gerektiğinde Perşembe ya da Cuma gününe alınabilir. Cumartesi 09:00 yalnız BYF ve Proje gruplarına açıktır; ÖYG 10:40’tan önce başlamaz. ÖYG/BYF en fazla 8, proje en fazla 3 öğrencidir.</p><div className="scheduleButtons"><button className="secondary" onClick={generate} disabled={busy||!students.length}>Yerel algoritmayla oluştur</button><button className="primary" onClick={generateAi} disabled={busy||!students.length}>{busy?"AI planlıyor…":"Güçlü AI ile program oluştur"} <span>↗</span></button></div></div>
    </section>
    {result&&<section className="results" id="results"><div className="resultHeader"><div><span>SONUÇLAR</span><h2>Programlar hazır</h2><p>{placedStudentCount}/{students.length} öğrenci · {result.studentRows.length} öğrenci-ders ataması · {result.rows.length} grup · {result.teacherNames.length} öğretmen</p>{result.unplaced.length>0&&<p><b>{result.unplaced.filter(x=>x.studentName).length} öğrenci yerleşemedi.</b> Adı ve kesin nedeni Uyarılar sekmesinde ve XLSX yönetim raporunda gösteriliyor.</p>}</div><div className="resultActions"><button onClick={()=>window.print()}>Yönetim PDF</button><button className="dark" onClick={()=>exportScheduleXlsx(result,options())}>Gerçek XLSX indir</button></div></div><div className="tabs"><button className={tab==="student"?"active":""} onClick={()=>setTab("student")}>Öğrenci programı <b>{placedStudentCount}</b></button><button className={tab==="group"?"active":""} onClick={()=>setTab("group")}>Grup programı <b>{result.rows.length}</b></button><button className={tab==="teacher"?"active":""} onClick={()=>setTab("teacher")}>Öğretmen programı <b>{result.teacherNames.length}</b></button><button className={tab==="issues"?"active":""} onClick={()=>setTab("issues")}>Uyarılar <b>{result.warnings.length+result.unplaced.length}</b></button></div>
      {tab==="student"&&<><div className="filters"><span>Öğrenci seçin</span><select value={studentFilter} onChange={e=>setStudentFilter(e.target.value)}>{[...new Set(result.studentRows.map(x=>x.student.name))].map(x=><option key={x}>{x}</option>)}</select></div><div className="studentCard"><div><small>ÖĞRENCİ PROGRAMI</small><h3>{studentFilter}</h3><p>{studentRows[0]?.student.grade} · {studentRows[0]?.student.school}</p></div><b>{studentRows.length} ders</b></div><div className="tableWrap"><table><thead><tr><th>Gün</th><th>Saat</th><th>Ders kodu</th><th>Öğretmen</th><th>Grup</th></tr></thead><tbody>{studentRows.map((x,i)=><tr key={i}><td><span className="dayDot"/>{x.row.day}</td><td>{x.row.time}</td><td><mark>{x.row.codes.join(" + ")}</mark></td><td>{x.row.teacher}</td><td>{x.row.students.length} öğrenci</td></tr>)}</tbody></table></div></>}
      {tab==="group"&&<div className="tableWrap topGap"><table><thead><tr><th>Gün</th><th>Saat</th><th>Ders kodu</th><th>Öğretmen</th><th>Öğrenci</th><th>Liste</th></tr></thead><tbody>{result.rows.map((x,i)=><tr key={i}><td>{x.day}</td><td>{x.time}</td><td><mark>{x.codes.join(" + ")}</mark></td><td>{x.teacher}</td><td>{x.students.length}</td><td>{x.students.map(s=>s.name).join(", ")}</td></tr>)}</tbody></table></div>}
      {tab==="teacher"&&<><div className="filters"><span>Öğretmen seçin</span><select value={teacherFilter} onChange={e=>setTeacherFilter(e.target.value)}>{result.teacherNames.map(x=><option key={x}>{x}</option>)}</select></div><div className="studentCard"><div><small>ÖĞRETMEN PROGRAMI</small><h3>{teacherFilter}</h3></div><b>{teacherRows.length} grup</b></div><div className="tableWrap"><table><thead><tr><th>Gün</th><th>Saat</th><th>Ders kodu</th><th>Öğrenci</th><th>Liste</th></tr></thead><tbody>{teacherRows.map((x,i)=><tr key={i}><td>{x.day}</td><td>{x.time}</td><td><mark>{x.codes.join(" + ")}</mark></td><td>{x.students.length}</td><td>{x.students.map(s=>s.name).join(", ")}</td></tr>)}</tbody></table></div></>}
      {tab==="issues"&&<div className="issues">{!result.warnings.length&&!result.unplaced.length?<div className="success">✓ Bütün öğrenciler kurallara uygun yerleştirildi.</div>:<>{result.unplaced.map((x,i)=><div key={`u${i}`}><b>{x.studentName||x.codes.join(" + ")||"Öğrenci verisi"}</b><span>{x.codes.length?`${x.codes.join(" + ")} — ${x.reason}`:x.reason}</span></div>)}{result.warnings.map((x,i)=><div key={`w${i}`}><b>Bilgi / uyarı</b><span>{x}</span></div>)}</>}</div>}
      <div className="printReport"><header><h1>BİLSEM Ders Programı</h1><p>Yönetim raporu · {new Date().toLocaleDateString("tr-TR")}</p><div><b>{placedStudentCount}/{students.length}</b> öğrenci · <b>{result.rows.length}</b> grup · <b>{result.teacherNames.length}</b> öğretmen</div></header>{result.unplaced.length>0&&<><h2>Yerleştirilemeyen öğrenciler ve nedenleri</h2><table><thead><tr><th>Öğrenci</th><th>Ders kodları</th><th>Neden</th></tr></thead><tbody>{result.unplaced.filter(x=>x.studentName).map((x,i)=><tr key={`pu${i}`}><td>{x.studentName}</td><td>{x.codes.join(" + ")||"—"}</td><td>{x.reason}</td></tr>)}</tbody></table></>}<h2>Genel grup programı</h2><table><thead><tr><th>Gün</th><th>Saat</th><th>Ders kodu</th><th>Öğretmen</th><th>Öğrenci sayısı</th></tr></thead><tbody>{result.rows.map((x,i)=><tr key={`pg${i}`}><td>{x.day}</td><td>{x.time}</td><td>{x.codes.join(" + ")}</td><td>{x.teacher}</td><td>{x.students.length}</td></tr>)}</tbody></table><h2>Öğretmen programları</h2>{result.teacherNames.map(name=><section className="printPerson" key={name}><h3>{name}</h3><table><thead><tr><th>Gün</th><th>Saat</th><th>Ders kodu</th><th>Öğrenciler</th></tr></thead><tbody>{result.rows.filter(x=>x.teacher===name).map((x,i)=><tr key={i}><td>{x.day}</td><td>{x.time}</td><td>{x.codes.join(" + ")}</td><td>{x.students.map(s=>s.name).join(", ")}</td></tr>)}</tbody></table></section>)}<h2>Öğrenci programları</h2>{[...new Set(result.studentRows.map(x=>x.student.name))].map(name=><section className="printPerson" key={name}><h3>{name}</h3><table><thead><tr><th>Gün</th><th>Saat</th><th>Ders kodu</th><th>Öğretmen</th></tr></thead><tbody>{result.studentRows.filter(x=>x.student.name===name).map((x,i)=><tr key={i}><td>{x.row.day}</td><td>{x.row.time}</td><td>{x.row.codes.join(" + ")}</td><td>{x.row.teacher}</td></tr>)}</tbody></table></section>)}</div>
    </section>}
    <section className="how" id="how"><div><span>NASIL ÇALIŞIR?</span><h2>İki Excel’den yönetim programına.</h2></div><ol><li><b>01</b><h3>Excel’leri yükleyin</h3><p>Öğrenci dersleri ve satır renkleri ile öğretmen–ders eşlemeleri okunur.</p></li><li><b>02</b><h3>Ana ÖYG kuralları uygulanır</h3><p>7. sınıf Salı, 8. sınıf Çarşamba; turuncular Cumartesi. İki ders aynı gün art arda planlanır.</p></li><li><b>03</b><h3>Programları alın</h3><p>Öğrenci ve öğretmen programlarını XLSX veya yönetim PDF’i olarak paylaşın.</p></li></ol></section>
    <footer><a className="brand" href="#">Ders<span>Plan</span></a><p>Ham Excel dosyaları gönderilmez. Güçlü AI seçilirse ders, öğretmen ve kısıt verileri seçilen API’ye gönderilir.</p></footer>
  </main>
}
