import ExcelJS from "exceljs";
import JSZip from "jszip";
import type {ScheduleOptions,ScheduleResult,Shift,Student,StudentColor,LessonRef,TeacherRecord} from "./scheduler";

const norm=(s:string)=>String(s||"").toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/[^a-z0-9]/g,"");
const valueText=(v:unknown):string=>{if(v==null)return"";if(typeof v==="object"&&v&&"text" in v)return String((v as {text:unknown}).text);if(typeof v==="object"&&v&&"result" in v)return String((v as {result:unknown}).result??"");return String(v)};
const findCol=(headers:string[],names:string[])=>{const wanted=names.map(norm);return headers.findIndex(h=>wanted.includes(norm(h)))};
const splitList=(s:string)=>s.split(/[|;]/).map(x=>x.trim()).filter(Boolean);
async function loadWorkbook(file:File){if(file.size>20_000_000)throw new Error("Excel dosyası 20 MB’den küçük olmalı.");const bytes=new Uint8Array(await file.arrayBuffer());try{const wb=new ExcelJS.Workbook();await wb.xlsx.load(bytes as never);return wb}catch{const zip=await JSZip.loadAsync(bytes);for(const [path,entry] of Object.entries(zip.files))if(path.startsWith("xl/")&&path.endsWith(".xml")&&!entry.dir){const xml=await entry.async("string");zip.file(path,xml.replace(/<\/?x:/g,tag=>tag.startsWith("</")?"</":"<"))}const normalized=await zip.generateAsync({type:"uint8array"});const wb=new ExcelJS.Workbook();await wb.xlsx.load(normalized as never);return wb}}
const parseLesson=(raw:string):LessonRef|null=>{const text=raw.trim();if(!text)return null;const code=text.toLocaleUpperCase("tr-TR").match(/^[ÖP]?[A-ZÇĞİÖŞÜ]{2,}\d{2,}/)?.[0]||text.split(/[ .]/)[0].toLocaleUpperCase("tr-TR");if(!code)return null;const day=text.match(/(Pazartesi|Salı|Çarşamba|Perşembe|Cumartesi|Cuma)/i)?.[1];const time=text.match(/(\d{1,2}:\d{2})\s*[-_]\s*(\d{1,2}:\d{2})/);return{code,raw:text,previousDay:day,previousTime:time?`${time[1].padStart(5,"0")}-${time[2].padStart(5,"0")}`:undefined}};
function inferShift(explicit:string,school:string):Shift{const n=norm(explicit||school);if(n.includes("sabah"))return"Sabah";if(n.includes("ogle"))return"Öğle";if(n.includes("tamgun"))return"Tam Gün";return"Bilinmiyor"}
function inferStudentColor(cell:ExcelJS.Cell):StudentColor{const fill=cell.fill;if(fill?.type!=="pattern")return"Yok";const argb=(fill.fgColor?.argb||"").toLocaleUpperCase("tr-TR");if(argb.endsWith("FFFF00"))return"Sarı";if(argb.endsWith("00B0F0"))return"Mavi";if(argb.endsWith("FFC000"))return"Turuncu";return"Yok"}
const branchByCode:Record<string,string>={"ÖKİM":"KİMYA","ÖMAT":"MATEMATİK","ÖBİL":"BİLİŞİM TEKNOLOJİLERİ","ÖBİY":"BİYOLOJİ","ÖTEK":"TEKNOLOJİ TASARIM","ÖFİZ":"FİZİK","ÖTAR":"TARİH","ÖEDB":"TÜRK DİLİ VE EDEBİYATI","ÖFEL":"FELSEFE","ÖCOĞ":"COĞRAFYA","ÖİNG":"İNGİLİZCE"};
function branchForCode(code:string){const prefix=code.toLocaleUpperCase("tr-TR").match(/^[ÖP]?[A-ZÇĞİÖŞÜ]+/)?.[0]||"";return branchByCode[prefix]}

export async function readStudentWorkbook(file:File):Promise<{students:Student[];sheetName:string;headers:string[];warnings:string[]}>{
  const wb=await loadWorkbook(file);const ws=wb.worksheets[0];if(!ws)throw new Error("Excel dosyasında çalışma sayfası bulunamadı.");
  const sourceRows:Array<{rowNumber:number;values:string[]}>=[];ws.eachRow({includeEmpty:false},(row,rowNumber)=>sourceRows.push({rowNumber,values:(row.values as unknown[]).slice(1).map(valueText)}));const matrix=sourceRows.map(x=>x.values);if(matrix.length<2)throw new Error("Excel dosyasında başlık ve öğrenci satırları bulunmalı.");
  const headers=matrix[0],nameI=findCol(headers,["İSİM VE SOYİSİM","AD SOYAD","ÖĞRENCİ","ÖĞRENCİ ADI","AD"]),gradeI=findCol(headers,["E-OKUL SINIFI (şimdi)","E-OKUL SINIFI","SINIF","GRUP"]),schoolI=findCol(headers,["E-OKUL DEVRESİ (şimdi)","E-OKUL DEVRESİ","OKUL","OKULU"]),shiftI=findCol(headers,["VARDİYA","OKUL VARDİYASI","SABAH/ÖĞLE"]),unavailableI=findCol(headers,["UYGUN OLMADIĞI SAATLER","UYGUN DEĞİL","MÜSAİT DEĞİL"]);
  if(nameI<0)throw new Error("Öğrenci adı sütunu bulunamadı. 'İSİM VE SOYİSİM' veya 'Ad Soyad' başlığı kullanın.");
  const lessonIndices=[findCol(headers,["ANA DERS"]),findCol(headers,["YAN ALAN"]),findCol(headers,["İKİNCİ ALAN"]),findCol(headers,["DERSLER","ALDIĞI DERSLER"])].filter((x,i,a)=>x>=0&&a.indexOf(x)===i);if(!lessonIndices.length)throw new Error("Ders sütunu bulunamadı. 'ANA DERS', 'YAN ALAN', 'İKİNCİ ALAN' veya 'Dersler' başlığı kullanın.");
  const warnings:string[]=[],students=matrix.slice(1).map((row,index)=>{const name=(row[nameI]||"").trim(),grade=gradeI>=0?(row[gradeI]||"").trim():"",school=schoolI>=0?(row[schoolI]||"").trim():"",rawLessons=lessonIndices.flatMap(i=>splitList(row[i]||"")),lessons=[...new Map(rawLessons.map(parseLesson).filter(Boolean).map(x=>[(x as LessonRef).code,x as LessonRef])).values()],excelRow=sourceRows[index+1].rowNumber;return{id:`ogrenci-${excelRow}`,name,grade,school,shift:inferShift(shiftI>=0?(row[shiftI]||""):"",school),color:inferStudentColor(ws.getCell(excelRow,nameI+1)),unavailable:unavailableI>=0?splitList(row[unavailableI]||""):[],lessons}}).filter(s=>s.name);
  const noLessons=students.filter(s=>!s.lessons.length).length;if(noLessons)warnings.push(`${noLessons} öğrencide ders kodu bulunamadı.`);return{students,sheetName:ws.name,headers,warnings};
}

export async function readTeacherWorkbook(file:File):Promise<{teachers:TeacherRecord[];warnings:string[]}>{
  const wb=await loadWorkbook(file);const ws=wb.worksheets[0];if(!ws)throw new Error("Öğretmen Excel’inde çalışma sayfası bulunamadı.");
  const matrix:string[][]=[];ws.eachRow({includeEmpty:false},row=>matrix.push((row.values as unknown[]).slice(1).map(valueText)));if(matrix.length<2)throw new Error("Öğretmen Excel’inde başlık ve öğretmen satırları bulunmalı.");
  const headers=matrix[0],nameI=findCol(headers,["ÖĞRETMEN ADI SOYADI","AD SOYAD","ÖĞRETMEN","ÖĞRETMEN ADI"]),codesI=findCol(headers,["DERS KODLARI","DERS KODU","KODLAR","DERSLER"]),availableI=findCol(headers,["UYGUN OLDUĞU SAATLER","UYGUN SAATLER","MÜSAİT SAATLER"]),unavailableI=findCol(headers,["UYGUN OLMADIĞI SAATLER","UYGUN DEĞİL","MÜSAİT DEĞİL"]),maxI=findCol(headers,["GÜNLÜK MAKSİMUM","GÜNLÜK DERS SINIRI","MAX GÜNLÜK"]);
  if(nameI>=0&&codesI<0&&headers.some(x=>/PERİYOT/i.test(x))){const records=new Map<string,{name:string;patterns:Set<string>}>();for(const scheduleSheet of wb.worksheets){const scheduleHeaders=(scheduleSheet.getRow(1).values as unknown[]).slice(1).map(valueText),teacherIndex=findCol(scheduleHeaders,["ÖĞRETMEN","ÖĞRETMEN ADI"]);if(teacherIndex<0)continue;scheduleSheet.eachRow({includeEmpty:false},(row,rowNumber)=>{if(rowNumber===1)return;const values=(row.values as unknown[]).slice(1).map(valueText),name=(values[teacherIndex]||"").trim();if(!name)return;const codes=values.slice(teacherIndex+1).flatMap(value=>value.split(/\r?\n/).slice(0,1)).map(value=>value.toLocaleUpperCase("tr-TR").match(/^[ÖP]?[A-ZÇĞİÖŞÜ]{2,}\d{2,}/)?.[0]).filter(Boolean) as string[];if(!codes.length)return;const key=norm(name),record=records.get(key)||{name,patterns:new Set<string>()};for(const code of codes){record.patterns.add(code);const branch=branchForCode(code);if(branch)record.patterns.add(branch)}records.set(key,record)})}const teachers=[...records.values()].map((record,index)=>({id:`t-program-${index+1}`,name:record.name,patterns:[...record.patterns],available:[],unavailable:[]}));if(!teachers.length)throw new Error("Program Excel’inde öğretmen ve ders kodu bulunamadı.");return{teachers,warnings:["Öğretmenler ve ders eşlemeleri mevcut program sayfalarından okundu; ayrıca uygunluk saatleri verilmediği için öğretmenler seçili tüm periyotlarda uygun kabul edildi."]}}
  if(nameI<0||codesI<0)throw new Error("Öğretmen Excel’inde 'ÖĞRETMEN ADI SOYADI' ve 'DERS KODLARI' başlıkları bulunmalı; alternatif olarak ÖĞRETMEN ve PERİYOT sütunlu program dosyası yükleyebilirsiniz.");
  const teachers:TeacherRecord[]=matrix.slice(1).map((row,index)=>{const name=(row[nameI]||"").trim(),patterns=splitList((row[codesI]||"").replace(/,/g,";")).map(x=>x.toLocaleUpperCase("tr-TR")),max=Number(maxI>=0?row[maxI]:"");return{id:`t-${index+2}-${norm(name)}`,name,patterns,available:availableI>=0?splitList(row[availableI]||""):[],unavailable:unavailableI>=0?splitList(row[unavailableI]||""):[],maxDaily:Number.isFinite(max)&&max>0?max:undefined}}).filter(x=>x.name);
  const warnings:string[]=[];const noCodes=teachers.filter(x=>!x.patterns.length);if(noCodes.length)warnings.push(`${noCodes.length} öğretmende ders kodu bulunamadı.`);return{teachers,warnings};
}

const headerStyle={font:{bold:true,color:{argb:"FFFFFFFF"}},fill:{type:"pattern",pattern:"solid",fgColor:{argb:"FF16211D"}},alignment:{vertical:"middle",horizontal:"center"}} as const;
const addRows=(ws:ExcelJS.Worksheet,headers:string[],rows:(string|number)[][],widths:number[])=>{ws.addRow(headers);rows.forEach(r=>ws.addRow(r));ws.getRow(1).eachCell(c=>Object.assign(c,headerStyle));ws.getRow(1).height=26;ws.views=[{state:"frozen",ySplit:1}];ws.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,rows.length+1),column:headers.length}};widths.forEach((w,i)=>ws.getColumn(i+1).width=w);ws.eachRow((row,n)=>{row.alignment={vertical:"middle",wrapText:true};if(n>1&&n%2===1)row.eachCell(c=>c.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFE7EFEA"}})});ws.pageSetup={orientation:"landscape",fitToPage:true,fitToWidth:1,fitToHeight:0};};
export async function exportScheduleXlsx(result:ScheduleResult,options:ScheduleOptions){
  const wb=new ExcelJS.Workbook();wb.creator="DersPlan";wb.created=new Date();
  const students=wb.addWorksheet("Öğrenci Programları");addRows(students,["Öğrenci","Sınıf","Okul","Renk","Vardiya","Gün","Saat","Ders Kodu","Öğretmen","Birleşim"],result.studentRows.map(x=>[x.student.name,x.student.grade,x.student.school,x.student.color,x.student.shift,x.row.day,x.row.time,x.row.codes.join(" + "),x.row.teacher,x.row.merged?"Evet":"Hayır"]),[25,14,38,12,12,13,16,22,25,11]);
  const groups=wb.addWorksheet("Grup Programı");addRows(groups,["Gün","Saat","Ders Kodu","Öğretmen","Öğrenci Sayısı","Öğrenciler","Not"],result.rows.map(x=>[x.day,x.time,x.codes.join(" + "),x.teacher,x.students.length,x.students.map(s=>s.name).join(", "),x.note]),[13,16,24,25,14,72,28]);
  const teachers=wb.addWorksheet("Öğretmen Programları");addRows(teachers,["Öğretmen","Gün","Saat","Ders Kodu","Öğrenci Sayısı","Öğrenciler"],result.rows.slice().sort((a,b)=>a.teacher.localeCompare(b.teacher,"tr")||a.day.localeCompare(b.day,"tr")||a.time.localeCompare(b.time)).map(x=>[x.teacher,x.day,x.time,x.codes.join(" + "),x.students.length,x.students.map(s=>s.name).join(", ")]),[26,13,16,24,14,80]);
  const availability=wb.addWorksheet("Öğretmen Uygunlukları");addRows(availability,["Öğretmen","Ders Kodları","Uygun Saatler","Uygun Olmayan Saatler","Günlük Maksimum"],options.teacherAvailability.map(x=>[x.name,x.patterns.join(" | "),x.available.join(" | "),x.unavailable.join(" | "),x.maxDaily||""]),[27,24,75,55,18]);
  const warnings=wb.addWorksheet("Uyarılar");addRows(warnings,["Tür","Açıklama"],[...result.warnings.map(x=>["Uyarı",x]),...result.unplaced.map(x=>["Yerleştirilemedi",`${x.codes.join(" + ")}: ${x.reason}`])],[20,110]);
  const settings=wb.addWorksheet("Ayarlar");addRows(settings,["Ayar","Değer"],[["Çalışma günleri",options.days.join(", ")],["Hafta içi saatleri",options.weekdaySlots.join(", ")],["Cumartesi saatleri",options.saturdaySlots.join(", ")],["Öğretmen eşlemeleri",options.teacherMapText],["Yazılı kurallar",options.customRules],["Öğrenci çakışması",options.preventStudentConflicts?"Engelle":"İzin ver"],["Öğretmen çakışması",options.preventTeacherConflicts?"Engelle":"İzin ver"]],[26,110]);
  const buffer=await wb.xlsx.writeBuffer();const blob=new Blob([buffer],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="ogrenci-ders-programlari.xlsx";a.click();URL.revokeObjectURL(url);
}
