export type Shift="Sabah"|"Öğle"|"Tam Gün"|"Bilinmiyor";
export type StudentColor="Sarı"|"Mavi"|"Turuncu"|"Yok";
export type LessonRef={code:string;raw:string;previousDay?:string;previousTime?:string};
export type Student={id:string;name:string;grade:string;school:string;shift:Shift;color:StudentColor;unavailable:string[];lessons:LessonRef[]};
export type TeacherRecord={id:string;name:string;patterns:string[];available:string[];unavailable:string[];maxDaily?:number};
export type ScheduleRow={day:string;time:string;codes:string[];teacher:string;students:Student[];merged:boolean;note:string};
export type ScheduleResult={rows:ScheduleRow[];studentRows:Array<{student:Student;row:ScheduleRow}>;warnings:string[];unplaced:Array<{studentId?:string;studentName?:string;codes:string[];reason:string}>;teacherNames:string[]};
export type AiAssignment={codes:string[];studentIds?:string[];day:string;time:string;teacher?:string;note?:string};
export type ScheduleOptions={days:string[];weekdaySlots:string[];fridaySlots?:string[];saturdaySlots:string[];teacherMapText:string;customRules:string;teacherAvailability:TeacherRecord[];preventStudentConflicts:boolean;preventTeacherConflicts:boolean;preferPrivateSaturday:boolean;preferMorningWeekday:boolean;preservePrevious:boolean;mergeWhenNeeded:boolean;mergeMax:number;maxStudentDaily:number;maxTeacherDaily:number};

const norm=(s:string)=>String(s||"").toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/[^a-z0-9*]/g,"");
const dayNorm=(s:string)=>{const n=norm(s);if(n.startsWith("sal"))return "Salı";if(n.startsWith("cumart"))return "Cumartesi";if(n.startsWith("pazart"))return "Pazartesi";if(n.startsWith("cars"))return "Çarşamba";if(n.startsWith("pers"))return "Perşembe";if(n==="cuma"||n.startsWith("cum"))return "Cuma";return s};
const stageKey=(code:string)=>{const m=code.toLocaleUpperCase("tr-TR").match(/^([ÖP]?[A-ZÇĞİÖŞÜ]+)(\d)/);return m?`${m[1]}${m[2]}`:code.replace(/\d+$/,'')};

// BİLSEM kapasite kuralı: P ile başlayan proje grupları en fazla 3,
// BYF/ÖYG ve diğer proje dışı gruplar en fazla 8 öğrenciden oluşur.
export function groupStudentLimit(codes:string[],configuredLimit=Number.POSITIVE_INFINITY){
  const curriculumLimit=codes.some(code=>String(code||"").trim().toLocaleUpperCase("tr-TR").startsWith("P"))?3:8;
  return Number.isFinite(configuredLimit)&&configuredLimit>0?Math.min(curriculumLimit,Math.floor(configuredLimit)):curriculumLimit;
}

export function parseTeacherMap(text:string){
  const entries:Array<{pattern:string;teacher:string}>=[];
  for(const raw of text.split(/[\n;]/)){const line=raw.trim();if(!line)continue;const eq=line.match(/^([^=]+)=([^=]+)$/);if(eq){entries.push({pattern:eq[1].trim().toLocaleUpperCase("tr-TR"),teacher:eq[2].trim()});continue}const colon=line.match(/^([^:]+):(.+)$/);if(colon){for(const p of colon[2].split(/[,|]/))entries.push({pattern:p.trim().toLocaleUpperCase("tr-TR"),teacher:colon[1].trim()})}}
  return entries;
}
function teacherFor(code:string,map:ReturnType<typeof parseTeacherMap>){const u=norm(code);const exact=map.find(x=>!norm(x.pattern).endsWith("*")&&norm(x.pattern)===u);if(exact)return exact.teacher;const wild=map.filter(x=>norm(x.pattern).endsWith("*")&&u.startsWith(norm(x.pattern).slice(0,-1))).sort((a,b)=>norm(b.pattern).length-norm(a.pattern).length)[0];return wild?.teacher||"Atanmamış"}
function teachersFor(code:string,map:ReturnType<typeof parseTeacherMap>){const u=norm(code),exact=map.filter(x=>!norm(x.pattern).endsWith("*")&&norm(x.pattern)===u).map(x=>x.teacher);if(exact.length)return[...new Set(exact)];const matches=map.filter(x=>norm(x.pattern).endsWith("*")&&u.startsWith(norm(x.pattern).slice(0,-1))),longest=Math.max(0,...matches.map(x=>norm(x.pattern).length));return[...new Set(matches.filter(x=>norm(x.pattern).length===longest).map(x=>x.teacher))]}

type ParsedRules={fixed:Map<string,{day:string;time?:string}>;studentUnavailable:Map<string,Set<string>>;teacherAllowed:Map<string,Set<string>>;teacherUnavailable:Map<string,Set<string>>;teacherMaxDaily:Map<string,number>;noMerge:Set<string>;warnings:string[]};
function parseRules(text:string,students:Student[],teachers:string[]):ParsedRules{
  const fixed=new Map<string,{day:string;time?:string}>(),studentUnavailable=new Map<string,Set<string>>(),teacherAllowed=new Map<string,Set<string>>(),teacherUnavailable=new Map<string,Set<string>>(),teacherMaxDaily=new Map<string,number>(),noMerge=new Set<string>(),warnings:string[]=[];
  for(const raw of text.split(/\n/)){
    const line=raw.trim();if(!line)continue;
    const upper=line.toLocaleUpperCase("tr-TR"),code=upper.match(/[ÖP]?[A-ZÇĞİÖŞÜ]{2,}\d{2,}/)?.[0];
    const dayMatches=[...line.matchAll(/(Pazartesi|Salı|Çarşamba|Perşembe|Cumartesi|Cuma)/gi)].map(x=>dayNorm(x[1])),dayMatch=dayMatches[0];
    const time=line.match(/(\d{1,2}:\d{2})\s*[-_]\s*(\d{1,2}:\d{2})/);
    if(code&&dayMatch){fixed.set(code,{day:dayMatch,time:time?`${time[1].padStart(5,"0")}-${time[2].padStart(5,"0")}`:undefined});if(/birleşmesin|birlestirme/i.test(line))noMerge.add(code);continue}
    if(code&&/birleşmesin|birlestirme/i.test(line)){noMerge.add(code);continue}
    const teacher=teachers.slice().sort((a,b)=>b.length-a.length).find(t=>norm(line).startsWith(norm(t)));
    if(teacher){let understood=false;if(dayMatches.length&&/yalnız|yalniz|sadece/i.test(line)){teacherAllowed.set(teacher,new Set(dayMatches));understood=true}else if(dayMatch&&/uygun değil|uygun degil|gelemez|çalışmaz|calismaz/i.test(line)){const set=teacherUnavailable.get(teacher)||new Set<string>();set.add(dayMatch);teacherUnavailable.set(teacher,set);understood=true}const maximum=line.match(/günde\s+(?:en\s+fazla\s+)?(\d+)/i);if(maximum){teacherMaxDaily.set(teacher,Number(maximum[1]));understood=true}if(understood)continue}
    const student=students.find(s=>norm(line).startsWith(norm(s.name)));if(student&&dayMatch&&/uygun değil|uygun degil|gelemez/i.test(line)){const set=studentUnavailable.get(student.id)||new Set<string>();set.add(dayMatch);studentUnavailable.set(student.id,set);continue}
    warnings.push(`Yazılı kural anlaşılamadı: “${line}”`)
  }
  return{fixed,studentUnavailable,teacherAllowed,teacherUnavailable,teacherMaxDaily,noMerge,warnings};
}

type Group={codes:string[];teacher:string;students:Student[];previousDay?:string;previousTime?:string;merged:boolean};
const uniqueStudents=(items:Student[])=>[...new Map(items.map(s=>[s.id,s])).values()];
const chunks=<T,>(items:T[],size:number)=>Array.from({length:Math.ceil(items.length/size)},(_,index)=>items.slice(index*size,(index+1)*size));
// Ana sistem talimatı her öğrenci için iki ders öngörür. Excel'deki ANA DERS
// ve YAN ALAN sırası korunur; varsa üçüncü alan zorunlu çifte dahil edilmez.
export const requiredLessons=(student:Student)=>student.lessons.slice(0,2);
export const hasArtDayException=(student:Student)=>student.lessons.some(lesson=>/^(?:Ö|P)?(?:RES|MÜZ|MUZ)/i.test(lesson.code)||/(müzik|muzik|resim|görsel\s*sanatlar)/i.test(lesson.raw));
// Kod sözleşmesi: P... proje, B.../BYF... bilim ve yetenek; kalan dersler ÖYG.
export const lessonProgramType=(code:string):"ÖYG"|"BYF"|"Proje"=>{const upper=String(code||"").trim().toLocaleUpperCase("tr-TR");if(upper.startsWith("P"))return"Proje";if(/^B(?:YF)?[A-ZÇĞİÖŞÜ]*\d/.test(upper)||upper.startsWith("BYF"))return"BYF";return"ÖYG"};
const lessonCanUseSaturdayNine=(code:string)=>lessonProgramType(code)!=="ÖYG";
function slotsForDay(options:ScheduleOptions,day:string){return day==="Cumartesi"?options.saturdaySlots:day==="Cuma"&&options.fridaySlots?.length?options.fridaySlots:options.weekdaySlots}
function slotsFor(options:ScheduleOptions){return options.days.flatMap(day=>slotsForDay(options,day).map((time,index)=>({day,time,index})))}
function isPrivateOrRemote(s:Student){return s.shift==="Tam Gün"||s.shift==="Öğle"||/(özel|kolej|açı|istanbul|izmir|bandırma|tam gün)/i.test(s.school)}
function studentDayAllowed(student:Student,day:string){const art=hasArtDayException(student),exception=art&&(day==="Perşembe"||day==="Cuma");if(student.color==="Turuncu")return day==="Cumartesi"||exception;const grade=norm(student.grade);if(grade.startsWith("7"))return day==="Salı"||exception;if(grade.startsWith("8"))return day==="Çarşamba"||exception;return day!=="Cumartesi"}
function studentPeriodAllowed(student:Student,day:string,index:number){if(day==="Cumartesi")return index>=0;if(student.color==="Mavi")return index===1||index===2;return index>=0&&index<=2}
function pairIsConsecutive(a:{day:string;index:number;time?:string},b:{day:string;index:number;time?:string}){if(a.day!==b.day||Math.abs(a.index-b.index)!==1)return false;if(!a.time||!b.time)return true;const first=a.index<b.index?a:b,second=a.index<b.index?b:a,toMinutes=(value:string)=>{const [hour,minute]=value.split(":").map(Number);return hour*60+minute},end=first.time!.split("-")[1],start=second.time!.split("-")[0];return Boolean(end&&start&&toMinutes(start)-toMinutes(end)<=30)}
function finalizeStudentPairs(rows:ScheduleRow[],students:Student[],options:ScheduleOptions,warnings:string[],unplaced:ScheduleResult["unplaced"]){
  const invalid=new Set<string>();
  for(const student of students){const required=requiredLessons(student),studentRows=rows.filter(row=>row.students.some(x=>x.id===student.id)),placements=studentRows.map(row=>({day:row.day,time:row.time,index:slotsForDay(options,row.day).indexOf(row.time)}));
    if(required.length<2){invalid.add(student.id);if(!unplaced.some(x=>x.studentId===student.id)){const reason=required.length===0?"Excel’de ANA DERS ve YAN ALAN kodu boş; model öğrencinin dersini uyduramaz.":`Excel’de yalnız ${required[0].code} var; art arda program için ikinci ders kodu eksik.`;unplaced.push({studentId:student.id,studentName:student.name,codes:required.map(x=>x.code),reason})}continue}
    if(placements.length!==2||!pairIsConsecutive(placements[0],placements[1])){invalid.add(student.id);if(!unplaced.some(x=>x.studentId===student.id)){const scheduled=studentRows.flatMap(row=>row.codes.filter(code=>required.some(lesson=>lesson.code===code))),missing=required.map(x=>x.code).filter(code=>!scheduled.includes(code)),detail=placements.length===0?"iki ders için geçerli grup üretilemedi":placements.length===1?`${missing.join(" + ")||"ikinci ders"} yerleştirilemedi`:`önerilen saatler aynı gün art arda değildi (${placements.map(x=>`${x.day} ${x.time}`).join(", ")})`;unplaced.push({studentId:student.id,studentName:student.name,codes:required.map(x=>x.code),reason:`${detail}; öğrencinin yarım programı sonuçtan çıkarıldı.`})}}
  }
  if(invalid.size){for(const row of rows)row.students=row.students.filter(student=>!invalid.has(student.id));warnings.push(`${invalid.size} öğrencinin eksik, farklı günlü veya ardışık olmayan ataması sonuçtan çıkarıldı.`)}
  for(const student of students.filter(x=>!invalid.has(x.id)&&hasArtDayException(x))){const day=rows.find(row=>row.students.some(x=>x.id===student.id))?.day,defaultDay=student.color==="Turuncu"?"Cumartesi":norm(student.grade).startsWith("7")?"Salı":norm(student.grade).startsWith("8")?"Çarşamba":"";if(day&&defaultDay&&day!==defaultDay)warnings.push(`${student.name}: Müzik/Resim istisnasıyla ${defaultDay} yerine ${day} gününe, iki dersi birlikte ve art arda yerleştirildi.`)}
  return rows.filter(row=>row.students.length);
}
function availabilityMatches(value:string,day:string,time:string){const n=norm(value);return n.includes(norm(day))&&(!/:/.test(value)||n.includes(norm(time.split("-")[0]))||n.includes(norm(time)))}
function teacherRecord(name:string,records:TeacherRecord[]){return records.find(x=>norm(x.name)===norm(name))}
function teacherCanTeach(name:string,day:string,time:string,records:TeacherRecord[]){const record=teacherRecord(name,records);if(!record)return true;if(record.unavailable.some(x=>availabilityMatches(x,day,time)))return false;return !record.available.length||record.available.some(x=>availabilityMatches(x,day,time))}

export function createStudentSchedule(students:Student[],options:ScheduleOptions):ScheduleResult{
  const map=parseTeacherMap(options.teacherMapText),mappedTeachers=[...new Set(map.map(x=>x.teacher))],rules=parseRules(options.customRules,students,mappedTeachers),warnings=[...rules.warnings];
  const grouped=new Map<string,Student[]>(),refs=new Map<string,LessonRef[]>();
  for(const s of students)for(const l of requiredLessons(s)){grouped.set(l.code,[...(grouped.get(l.code)||[]),s]);refs.set(l.code,[...(refs.get(l.code)||[]),l])}
  let groups:Group[]=[...grouped].flatMap(([code,list])=>{const r=refs.get(code)||[];const days=r.map(x=>x.previousDay).filter(Boolean) as string[],times=r.map(x=>x.previousTime).filter(Boolean) as string[],studentsForCode=uniqueStudents(list),limit=groupStudentLimit([code],options.mergeMax);if(studentsForCode.length>limit)warnings.push(`${code}: ${studentsForCode.length} öğrenci, grup başına ${limit} sınırı nedeniyle ${Math.ceil(studentsForCode.length/limit)} gruba bölündü.`);return chunks(studentsForCode,limit).map(groupStudents=>({codes:[code],teacher:teacherFor(code,map),students:groupStudents,previousDay:days.sort((a,b)=>days.filter(x=>x===b).length-days.filter(x=>x===a).length)[0],previousTime:times.sort((a,b)=>times.filter(x=>x===b).length-times.filter(x=>x===a).length)[0],merged:false}))});
  const allSlots=slotsFor(options),capacity=allSlots.length;
  if(options.mergeWhenNeeded){
    const teachers=[...new Set(groups.map(g=>g.teacher).filter(x=>x!=="Atanmamış"))];
    for(const teacher of teachers){let mine=groups.filter(g=>g.teacher===teacher);while(mine.length>capacity){let best:[Group,Group]|undefined;for(let i=0;i<mine.length;i++)for(let j=i+1;j<mine.length;j++){const a=mine[i],b=mine[j];if(stageKey(a.codes[0])!==stageKey(b.codes[0])||a.codes.some(c=>rules.noMerge.has(c))||b.codes.some(c=>rules.noMerge.has(c)))continue;const mergedCodes=[...a.codes,...b.codes],size=uniqueStudents([...a.students,...b.students]).length;if(size>groupStudentLimit(mergedCodes,options.mergeMax))continue;if(!best||size<uniqueStudents([...best[0].students,...best[1].students]).length)best=[a,b]}if(!best)break;const [a,b]=best,merged:Group={codes:[...a.codes,...b.codes],teacher,students:uniqueStudents([...a.students,...b.students]),previousDay:a.previousDay===b.previousDay?a.previousDay:undefined,previousTime:a.previousTime===b.previousTime?a.previousTime:undefined,merged:true};groups=groups.filter(g=>g!==a&&g!==b).concat(merged);mine=groups.filter(g=>g.teacher===teacher);warnings.push(`${a.codes.join("+")} ile ${b.codes.join("+")} aynı öğretmenin programına sığması için birleştirildi.`)}}
  }
  groups.sort((a,b)=>{const af=a.codes.some(c=>rules.fixed.has(c))?0:1,bf=b.codes.some(c=>rules.fixed.has(c))?0:1;return af-bf||b.students.length-a.students.length});
  let rows:ScheduleRow[]=[],unplaced:ScheduleResult["unplaced"]=[],studentBusy=new Set<string>(),teacherBusy=new Set<string>(),studentDaily=new Map<string,number>(),teacherDaily=new Map<string,number>(),studentPlacements=new Map<string,Array<{day:string;time:string;index:number}>>();
  for(const g of groups){const fixed=g.codes.map(c=>rules.fixed.get(c)).find(Boolean);let best:{day:string;time:string;index:number;score:number}|undefined;
    for(const slot of allSlots){if(fixed&&(slot.day!==fixed.day||(fixed.time&&slot.time!==fixed.time)))continue;if(slot.day==="Cumartesi"&&slot.time.startsWith("09:00")&&g.codes.some(code=>!lessonCanUseSaturdayNine(code)))continue;const allowed=rules.teacherAllowed.get(g.teacher),teacherUnavailable=rules.teacherUnavailable.get(g.teacher);if((allowed&&!allowed.has(slot.day))||teacherUnavailable?.has(slot.day)||!teacherCanTeach(g.teacher,slot.day,slot.time,options.teacherAvailability))continue;let invalid=false;for(const s of g.students){const custom=rules.studentUnavailable.get(s.id),placements=studentPlacements.get(s.id)||[];if(!studentDayAllowed(s,slot.day)||!studentPeriodAllowed(s,slot.day,slot.index)){invalid=true;break}if(placements.length&&!pairIsConsecutive(placements[0],slot)){invalid=true;break}if(custom?.has(slot.day)||s.unavailable.some(x=>norm(x).includes(norm(slot.day))&&(norm(x).includes(norm(slot.time.split('-')[0]))||!/:/.test(x)))){invalid=true;break}if(options.preventStudentConflicts&&studentBusy.has(`${s.id}|${slot.day}|${slot.time}`)){invalid=true;break}if((studentDaily.get(`${s.id}|${slot.day}`)||0)>=options.maxStudentDaily){invalid=true;break}}if(invalid)continue;if(options.preventTeacherConflicts&&g.teacher!=="Atanmamış"&&teacherBusy.has(`${g.teacher}|${slot.day}|${slot.time}`))continue;const teacherLimit=teacherRecord(g.teacher,options.teacherAvailability)?.maxDaily??rules.teacherMaxDaily.get(g.teacher)??options.maxTeacherDaily;if(g.teacher!=="Atanmamış"&&(teacherDaily.get(`${g.teacher}|${slot.day}`)||0)>=teacherLimit)continue;
      let score=slot.index*.1;if(g.students.some(s=>s.color==="Sarı"))score+=slot.index*2;if(slot.day==="Cumartesi"){const seventh=g.students.filter(s=>norm(s.grade).startsWith("7")).length,eighth=g.students.filter(s=>norm(s.grade).startsWith("8")).length,offset=options.saturdaySlots.some(time=>time.startsWith("09:00"))?1:0;score+=seventh*Math.min(Math.abs(slot.index-(1+offset)),Math.abs(slot.index-(2+offset)))*2+eighth*Math.min(Math.abs(slot.index-(2+offset)),Math.abs(slot.index-(3+offset)))*2}if(options.preferPrivateSaturday){const privateCount=g.students.filter(isPrivateOrRemote).length;score+=slot.day==="Cumartesi"?-privateCount*4:privateCount*4}if(options.preferMorningWeekday){const morning=g.students.filter(s=>s.shift==="Sabah").length;score+=slot.day==="Cumartesi"?morning*2:-morning*2}if(options.preservePrevious){if(g.previousDay&&slot.day===dayNorm(g.previousDay))score-=5;if(g.previousTime&&slot.time===g.previousTime.replace('_','-'))score-=2}const teacherDay=teacherDaily.get(`${g.teacher}|${slot.day}`)||0;score+=teacherDay*1.5;if(!best||score<best.score)best={...slot,score}}
    if(!best){unplaced.push({codes:g.codes,reason:fixed?"Sabitlenen gün/saatte çakışma veya kapasite sınırı var":"Uygun boş zaman veya ardışık öğrenci periyodu bulunamadı"});continue}const row:ScheduleRow={day:best.day,time:best.time,codes:g.codes,teacher:g.teacher,students:g.students,merged:g.merged,note:g.merged?"Birleştirilmiş grup":""};rows.push(row);for(const s of g.students){studentBusy.add(`${s.id}|${best.day}|${best.time}`);studentDaily.set(`${s.id}|${best.day}`,(studentDaily.get(`${s.id}|${best.day}`)||0)+1);studentPlacements.set(s.id,[...(studentPlacements.get(s.id)||[]),{day:best.day,time:best.time,index:best.index}])}if(g.teacher!=="Atanmamış"){teacherBusy.add(`${g.teacher}|${best.day}|${best.time}`);teacherDaily.set(`${g.teacher}|${best.day}`,(teacherDaily.get(`${g.teacher}|${best.day}`)||0)+1)}}
  if(groups.some(g=>g.teacher==="Atanmamış"))warnings.push("Bazı ders kodlarına öğretmen eşleştirilmedi; bu gruplar öğrenci çakışmasına göre planlandı.");
  for(const s of students.filter(x=>x.lessons.length>2))warnings.push(`${s.name}: ana talimattaki iki ders kuralı gereği ${requiredLessons(s).map(x=>x.code).join(" + ")} planlandı; ek alan ${s.lessons.slice(2).map(x=>x.code).join(" + ")} zorunlu çifte dahil edilmedi.`);
  rows=finalizeStudentPairs(rows,students,options,warnings,unplaced);const dayOrder=new Map(options.days.map((d,i)=>[d,i]));rows.sort((a,b)=>(dayOrder.get(a.day)??99)-(dayOrder.get(b.day)??99)||a.time.localeCompare(b.time,"tr"));
  const studentRows=rows.flatMap(row=>row.students.map(student=>({student,row}))).sort((a,b)=>a.student.name.localeCompare(b.student.name,"tr")||(dayOrder.get(a.row.day)??99)-(dayOrder.get(b.row.day)??99)||a.row.time.localeCompare(b.row.time));
  return{rows,studentRows,warnings,unplaced,teacherNames:[...new Set(rows.map(r=>r.teacher))].sort((a,b)=>a.localeCompare(b,"tr"))};
}

export function createScheduleFromAi(students:Student[],options:ScheduleOptions,assignments:AiAssignment[],aiWarnings:string[]=[]):ScheduleResult{
  const map=parseTeacherMap(options.teacherMapText),mappedTeachers=[...new Set(map.map(x=>x.teacher))],rules=parseRules(options.customRules,students,mappedTeachers),warnings=[...rules.warnings,...aiWarnings],unplaced:ScheduleResult["unplaced"]=[];
  const studentsByCode=new Map<string,Student[]>();for(const student of students)for(const lesson of requiredLessons(student))studentsByCode.set(lesson.code,[...(studentsByCode.get(lesson.code)||[]),student]);
  const studentsById=new Map(students.map(student=>[student.id,student])),knownCodes=new Set(studentsByCode.keys()),resolveCode=(raw:string)=>{const upper=String(raw||"").toLocaleUpperCase("tr-TR");if(knownCodes.has(upper))return upper;const normalized=norm(upper),matches=[...knownCodes].filter(code=>norm(code)===normalized||norm(code).startsWith(normalized)||normalized.startsWith(norm(code)));return matches.length===1?matches[0]:undefined},usedStudentCourses=new Set<string>(),slotLookup=new Map(slotsFor(options).map(x=>[`${x.day}|${x.time}`,x])),validSlots=new Set(slotLookup.keys());let rows:ScheduleRow[]=[];
  const studentBusy=new Set<string>(),teacherBusy=new Set<string>(),studentDaily=new Map<string,number>(),teacherDaily=new Map<string,number>(),studentPlacements=new Map<string,Array<{day:string;time:string;index:number}>>();
  for(const proposal of assignments){
    const codes=[...new Set((proposal.codes||[]).map(x=>resolveCode(String(x))).filter((code):code is string=>Boolean(code)))];if(!codes.length){warnings.push("AI, Excel’de bulunmayan bir ders kodu önerdi; satır atlandı.");continue}
    const requestedIds=[...new Set((proposal.studentIds||[]).map(String))],groupStudents=requestedIds.length?requestedIds.map(id=>studentsById.get(id)).filter((student):student is Student=>Boolean(student)&&codes.some(code=>requiredLessons(student!).some(lesson=>lesson.code===code))):uniqueStudents(codes.flatMap(code=>studentsByCode.get(code)||[]));if(!groupStudents.length){unplaced.push({codes,reason:"AI grubunda geçerli öğrenci bulunamadı"});continue}
    const coverageKeys=groupStudents.flatMap(student=>codes.filter(code=>requiredLessons(student).some(lesson=>lesson.code===code)).map(code=>`${student.id}|${code}`));if(coverageKeys.some(key=>usedStudentCourses.has(key))){unplaced.push({codes,reason:"AI aynı öğrenci–ders eşleşmesini birden fazla gruba yerleştirdi"});continue}
    const day=dayNorm(proposal.day),time=String(proposal.time||"").replace("_","-"),slot=slotLookup.get(`${day}|${time}`);if(!validSlots.has(`${day}|${time}`)||!slot){unplaced.push({codes,reason:"AI geçersiz gün veya saat bloğu önerdi"});continue}if(day==="Cumartesi"&&time.startsWith("09:00")&&codes.some(code=>!lessonCanUseSaturdayNine(code))){unplaced.push({codes,reason:"Cumartesi 09:00 periyodu yalnız BYF ve Proje içindir; ÖYG bu saatte planlanamaz"});continue}
    if(codes.length>1&&(codes.some(code=>rules.noMerge.has(code))||!options.mergeWhenNeeded)){unplaced.push({codes,reason:"Bu ders kodlarının birleştirilmesine izin verilmiyor"});continue}
    const groupLimit=groupStudentLimit(codes,options.mergeMax);if(groupStudents.length>groupLimit){unplaced.push({codes,reason:`Grup ${groupStudents.length} öğrenci içeriyor; ${codes.some(code=>code.startsWith("P"))?"proje":"BYF/ÖYG"} üst sınırı ${groupLimit}`});continue}
    const teacherCandidates=[...new Set(codes.flatMap(code=>teachersFor(code,map)))],proposedTeacher=String(proposal.teacher||"").trim();const teacher=teacherCandidates.find(name=>norm(name)===norm(proposedTeacher))||teacherCandidates[0]||proposedTeacher||"Atanmamış";const fixed=codes.map(code=>rules.fixed.get(code)).find(Boolean);if(fixed&&(fixed.day!==day||(fixed.time&&fixed.time!==time))){unplaced.push({codes,reason:"AI sabit gün/saat kuralına uymadı"});continue}
    const allowed=rules.teacherAllowed.get(teacher),teacherUnavailable=rules.teacherUnavailable.get(teacher);if((allowed&&!allowed.has(day))||teacherUnavailable?.has(day)||!teacherCanTeach(teacher,day,time,options.teacherAvailability)){unplaced.push({codes,reason:"AI öğretmenin gün/saat uygunluk kuralına uymadı"});continue}
    let reason="";for(const student of groupStudents){const placements=studentPlacements.get(student.id)||[];if(!studentDayAllowed(student,day)){reason=`${student.name} sınıf/renk gün kuralına uymuyor`;break}if(!studentPeriodAllowed(student,day,slot.index)){reason=`${student.name} renk periyot kuralına uymuyor`;break}if(placements.length&&!pairIsConsecutive(placements[0],slot)){reason=`${student.name} dersleri aynı gün art arda değil`;break}if(rules.studentUnavailable.get(student.id)?.has(day)||student.unavailable.some(x=>norm(x).includes(norm(day))&&(norm(x).includes(norm(time.split("-")[0]))||!/:/.test(x)))){reason=`${student.name} bu gün/saatte uygun değil`;break}if(options.preventStudentConflicts&&studentBusy.has(`${student.id}|${day}|${time}`)){reason=`${student.name} için saat çakışması`;break}if((studentDaily.get(`${student.id}|${day}`)||0)>=options.maxStudentDaily){reason=`${student.name} günlük ders sınırını aşıyor`;break}}
    if(!reason&&options.preventTeacherConflicts&&teacher!=="Atanmamış"&&teacherBusy.has(`${teacher}|${day}|${time}`))reason=`${teacher} için saat çakışması`;const teacherLimit=teacherRecord(teacher,options.teacherAvailability)?.maxDaily??rules.teacherMaxDaily.get(teacher)??options.maxTeacherDaily;if(!reason&&teacher!=="Atanmamış"&&(teacherDaily.get(`${teacher}|${day}`)||0)>=teacherLimit)reason=`${teacher} günlük grup sınırını aşıyor`;if(reason){unplaced.push({codes,reason});continue}
    const row:ScheduleRow={day,time,codes,teacher,students:groupStudents,merged:codes.length>1,note:proposal.note||"AI tarafından planlandı"};rows.push(row);coverageKeys.forEach(key=>usedStudentCourses.add(key));for(const student of groupStudents){studentBusy.add(`${student.id}|${day}|${time}`);studentDaily.set(`${student.id}|${day}`,(studentDaily.get(`${student.id}|${day}`)||0)+1);studentPlacements.set(student.id,[...(studentPlacements.get(student.id)||[]),{day,time,index:slot.index}])}if(teacher!=="Atanmamış"){teacherBusy.add(`${teacher}|${day}|${time}`);teacherDaily.set(`${teacher}|${day}`,(teacherDaily.get(`${teacher}|${day}`)||0)+1)}
  }
  // Güçlü model bir öğrenciyi atlarsa veya iki dersini yanlış çiftte önerirse,
  // mevcut grupları bozmadan yalnız o öğrencinin iki dersini deterministik onar.
  for(const student of students){const required=requiredLessons(student);if(required.length!==2)continue;const current=rows.filter(row=>row.students.some(x=>x.id===student.id)),currentPlacements=current.map(row=>({day:row.day,time:row.time,index:slotsForDay(options,row.day).indexOf(row.time)}));if(currentPlacements.length===2&&pairIsConsecutive(currentPlacements[0],currentPlacements[1]))continue;
    for(const row of rows)row.students=row.students.filter(x=>x.id!==student.id);rows=rows.filter(row=>row.students.length);const candidates=slotsFor(options).filter(slot=>studentDayAllowed(student,slot.day)&&studentPeriodAllowed(student,slot.day,slot.index)&&!rules.studentUnavailable.get(student.id)?.has(slot.day)&&!student.unavailable.some(x=>norm(x).includes(norm(slot.day))&&(norm(x).includes(norm(slot.time.split("-")[0]))||!/:/.test(x))));let best:{score:number;plans:Array<{row?:ScheduleRow;created?:ScheduleRow;student:Student}>}|undefined;
    for(let i=0;i<candidates.length;i++)for(let j=i+1;j<candidates.length;j++){const first=candidates[i],second=candidates[j];if(!pairIsConsecutive(first,second))continue;for(const ordered of [[required[0],first,required[1],second],[required[1],first,required[0],second]] as const){const pairs=[[ordered[0],ordered[1]],[ordered[2],ordered[3]]] as const,plans:Array<{row?:ScheduleRow;created?:ScheduleRow;student:Student}>=[];let score=0,valid=true;for(const [lesson,slot] of pairs){if(slot.day==="Cumartesi"&&slot.time.startsWith("09:00")&&!lessonCanUseSaturdayNine(lesson.code)){valid=false;break}const fixed=rules.fixed.get(lesson.code);if(fixed&&(fixed.day!==slot.day||(fixed.time&&fixed.time!==slot.time))){valid=false;break}const limit=groupStudentLimit([lesson.code],options.mergeMax),existing=rows.find(row=>row.day===slot.day&&row.time===slot.time&&row.codes.includes(lesson.code)&&row.students.length<limit);if(existing){plans.push({row:existing,student});continue}const teacherCandidates=teachersFor(lesson.code,map),teacher=(teacherCandidates.length?teacherCandidates:[teacherFor(lesson.code,map)]).find(name=>{const allowed=rules.teacherAllowed.get(name),blocked=rules.teacherUnavailable.get(name);if((allowed&&!allowed.has(slot.day))||blocked?.has(slot.day)||!teacherCanTeach(name,slot.day,slot.time,options.teacherAvailability))return false;if(name!=="Atanmamış"&&rows.some(row=>row.day===slot.day&&row.time===slot.time&&row.teacher===name))return false;const plannedSameDay=plans.filter(plan=>plan.created?.teacher===name&&plan.created.day===slot.day).length,dayCount=rows.filter(row=>row.teacher===name&&row.day===slot.day).length,teacherLimit=teacherRecord(name,options.teacherAvailability)?.maxDaily??rules.teacherMaxDaily.get(name)??options.maxTeacherDaily;return name==="Atanmamış"||dayCount+plannedSameDay<teacherLimit});if(!teacher){valid=false;break}plans.push({created:{day:slot.day,time:slot.time,codes:[lesson.code],teacher,students:[student],merged:false,note:"Eksik öğrenci güvenlik onarımı"},student});score+=10}
      if(valid){score+=first.index*.1;if(student.color==="Sarı")score+=first.index;if(!best||score<best.score)best={score,plans}}}}
    if(best){for(const plan of best.plans)if(plan.row)plan.row.students.push(student);else if(plan.created)rows.push(plan.created);warnings.push(`${student.name}: eksik veya uygunsuz AI çifti, kurallara uygun iki ardışık periyotta otomatik tamamlandı.`)}
  }
  for(const student of students.filter(x=>x.lessons.length>2))warnings.push(`${student.name}: ana talimattaki iki ders kuralı gereği ${requiredLessons(student).map(x=>x.code).join(" + ")} planlandı; ek alan ${student.lessons.slice(2).map(x=>x.code).join(" + ")} zorunlu çifte dahil edilmedi.`);
  rows=finalizeStudentPairs(rows,students,options,warnings,unplaced);const dayOrder=new Map(options.days.map((d,i)=>[d,i]));rows.sort((a,b)=>(dayOrder.get(a.day)??99)-(dayOrder.get(b.day)??99)||a.time.localeCompare(b.time,"tr"));const studentRows=rows.flatMap(row=>row.students.map(student=>({student,row}))).sort((a,b)=>a.student.name.localeCompare(b.student.name,"tr")||(dayOrder.get(a.row.day)??99)-(dayOrder.get(b.row.day)??99)||a.row.time.localeCompare(b.row.time));
  if(unplaced.length)warnings.push("AI önerisinin kurallara uymayan bölümleri güvenlik doğrulamasında reddedildi.");return{rows,studentRows,warnings,unplaced,teacherNames:[...new Set(rows.map(r=>r.teacher))].sort((a,b)=>a.localeCompare(b,"tr"))};
}
